redis:
  host: "redis_for_osm"
  port: 6379
  database: 0 # редис дб не имеют имени, они индексируются с 0
  password_env_name: "REDIS_PASSWORD"
telegram_bot:
  token_env_name: "BOT_TOKEN"
  workers_count: 1
osm_broker:
  categories_to_amenities_map:
    "Питание":
      "name": "Питание"
      "amenities":
        [
          "bar",
          "biergarten",
          "cafe",
          "fast_food",
          "food_court",
          "ice_cream",
          "pub",
          "restaurant",
        ]
    "Образование":
      "name": "Образование"
      "amenities":
        [
          "college",
          "driving_school",
          "kindergarten",
          "language_school",
          "library",
          "music_school",
          "school",
          "university",
        ]
    "Транспорт":
      "name": "Транспорт"
      "amenities":
        [
          "bicycle_parking",
          "bicycle_rental",
          "bus_station",
          "car_rental",
          "car_wash",
          "vehicle_inspection",
          "charging_station",
          "fuel",
          "motorcycle_parking",
          "parking",
          "taxi",
        ]
    "Финансы":
      "name": "Финансы"
      "amenities": 
        [
          "atm",
          "bank",
          "bureau_de_change",
        ]
    "Здоровье":
      "name": "Здоровье"
      "amenities":
        [
          "clinic",
          "dentist",
          "doctors",
          "hospital",
          "pharmacy",
          "veterinary",
        ]
    "Развлечение":
      "name": "Развлечение"
      "amenities":
        [
          "casino",
          "cinema",
          "community_centre",
          "conference_centre",
          "events_venue",
          "exhibition_centre",
          "music_venue",
          "nightclub",
          "planetarium",
          "public_bookcase",
          "theatre",
        ]
    "Общественное":
      "name": "Общественное"
      "amenities": 
        [
          "bbq",
          "drinking_water",
          "townhall", 
          "post_office",
          "parcel_locker",
          "shower",
          "telephone",
          "toilets",
          "water_point",
          "marketplace",
          "place_of_worship",
        ]
    "Другое":
      "name": "Другое"
      "amenities": 
        [
          "recycling", 
          "waste_disposal",
          "photo_booth",
          "grave_yard",
          "animal_shelter",
        ]
