version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "mapper"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 3
