version: "3.8"

services:
  redis:
    image: redis
    container_name: redis_for_osm
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./redis-d–∞ta:/root/redis
      - ./config.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    env_file:
      - .env
    restart: always
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: main
    env_file:
      - .env
    restart: always
    volumes:
      - ./controllers:/bot/controllers
      - ./cmd:/bot/cmd
      - ./dal:/bot/dal
      - ./services:/bot/services
      - ./config.yaml:/bot/config.yaml
      - ./main.py:/bot/main.py
